### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by sametserpil** [ExidCuter/YoutubeSearch4J#1]
`doc.select(".yt-lockup-content");` returning 0 elements. I think Youtube changed the page structure

**Comment by captain-nemo1** [comment]
Yes. Youtube has changed its pages so that they only load up when javascript is enabled. Otherwise its just unnecessary info in the code of the page.

**Comment by ExidCuter** [comment]
Yes. As @captain-nemo1 said Youtube finally switched to JS loading. So in current state this project is "useless". I am currently looking into parsing videos from duckduckgo. Will update on progress.
